/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeighBridgeRouteImport } from './routes/weigh-bridge'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DamsRouteImport } from './routes/dams'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ApiTrucksRouteImport } from './routes/api.trucks'
import { Route as ApiReportsRouteImport } from './routes/api.reports'
import { Route as ApiLoadsRouteImport } from './routes/api.loads'
import { Route as ApiDamsRouteImport } from './routes/api.dams'
import { Route as ApiAuditLogsRouteImport } from './routes/api.audit-logs'
import { Route as ApiTrucksIdRouteImport } from './routes/api.trucks.$id'
import { Route as ApiReportsIdRouteImport } from './routes/api.reports.$id'
import { Route as ApiDashboardSummaryRouteImport } from './routes/api.dashboard.summary'
import { Route as ApiDamsIdRouteImport } from './routes/api.dams.$id'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiReportsIdVersionsRouteImport } from './routes/api.reports.$id.versions'
import { Route as ApiReportsIdDownloadRouteImport } from './routes/api.reports.$id.download'

const WeighBridgeRoute = WeighBridgeRouteImport.update({
  id: '/weigh-bridge',
  path: '/weigh-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DamsRoute = DamsRouteImport.update({
  id: '/dams',
  path: '/dams',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const ApiTrucksRoute = ApiTrucksRouteImport.update({
  id: '/api/trucks',
  path: '/api/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadsRoute = ApiLoadsRouteImport.update({
  id: '/api/loads',
  path: '/api/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDamsRoute = ApiDamsRouteImport.update({
  id: '/api/dams',
  path: '/api/dams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsRoute = ApiAuditLogsRouteImport.update({
  id: '/api/audit-logs',
  path: '/api/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrucksIdRoute = ApiTrucksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTrucksRoute,
} as any)
const ApiReportsIdRoute = ApiReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReportsRoute,
} as any)
const ApiDashboardSummaryRoute = ApiDashboardSummaryRouteImport.update({
  id: '/api/dashboard/summary',
  path: '/api/dashboard/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDamsIdRoute = ApiDamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDamsRoute,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdVersionsRoute = ApiReportsIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReportsIdDownloadRoute = ApiReportsIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dams': typeof DamsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/weigh-bridge': typeof WeighBridgeRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/dams': typeof ApiDamsRouteWithChildren
  '/api/loads': typeof ApiLoadsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/trucks': typeof ApiTrucksRouteWithChildren
  '/reports/$id': typeof ReportsIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dams/$id': typeof ApiDamsIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/trucks/$id': typeof ApiTrucksIdRoute
  '/api/reports/$id/download': typeof ApiReportsIdDownloadRoute
  '/api/reports/$id/versions': typeof ApiReportsIdVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dams': typeof DamsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/weigh-bridge': typeof WeighBridgeRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/dams': typeof ApiDamsRouteWithChildren
  '/api/loads': typeof ApiLoadsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/trucks': typeof ApiTrucksRouteWithChildren
  '/reports/$id': typeof ReportsIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dams/$id': typeof ApiDamsIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/trucks/$id': typeof ApiTrucksIdRoute
  '/api/reports/$id/download': typeof ApiReportsIdDownloadRoute
  '/api/reports/$id/versions': typeof ApiReportsIdVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dams': typeof DamsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/weigh-bridge': typeof WeighBridgeRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/dams': typeof ApiDamsRouteWithChildren
  '/api/loads': typeof ApiLoadsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/trucks': typeof ApiTrucksRouteWithChildren
  '/reports/$id': typeof ReportsIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dams/$id': typeof ApiDamsIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/trucks/$id': typeof ApiTrucksIdRoute
  '/api/reports/$id/download': typeof ApiReportsIdDownloadRoute
  '/api/reports/$id/versions': typeof ApiReportsIdVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/dams'
    | '/dashboard'
    | '/history'
    | '/import'
    | '/insights'
    | '/onboarding'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/weigh-bridge'
    | '/api/audit-logs'
    | '/api/dams'
    | '/api/loads'
    | '/api/reports'
    | '/api/trucks'
    | '/reports/$id'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/dams/$id'
    | '/api/dashboard/summary'
    | '/api/reports/$id'
    | '/api/trucks/$id'
    | '/api/reports/$id/download'
    | '/api/reports/$id/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/dams'
    | '/dashboard'
    | '/history'
    | '/import'
    | '/insights'
    | '/onboarding'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/weigh-bridge'
    | '/api/audit-logs'
    | '/api/dams'
    | '/api/loads'
    | '/api/reports'
    | '/api/trucks'
    | '/reports/$id'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/dams/$id'
    | '/api/dashboard/summary'
    | '/api/reports/$id'
    | '/api/trucks/$id'
    | '/api/reports/$id/download'
    | '/api/reports/$id/versions'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/dams'
    | '/dashboard'
    | '/history'
    | '/import'
    | '/insights'
    | '/onboarding'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/weigh-bridge'
    | '/api/audit-logs'
    | '/api/dams'
    | '/api/loads'
    | '/api/reports'
    | '/api/trucks'
    | '/reports/$id'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/dams/$id'
    | '/api/dashboard/summary'
    | '/api/reports/$id'
    | '/api/trucks/$id'
    | '/api/reports/$id/download'
    | '/api/reports/$id/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  DamsRoute: typeof DamsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  ImportRoute: typeof ImportRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WeighBridgeRoute: typeof WeighBridgeRoute
  ApiAuditLogsRoute: typeof ApiAuditLogsRoute
  ApiDamsRoute: typeof ApiDamsRouteWithChildren
  ApiLoadsRoute: typeof ApiLoadsRoute
  ApiReportsRoute: typeof ApiReportsRouteWithChildren
  ApiTrucksRoute: typeof ApiTrucksRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDashboardSummaryRoute: typeof ApiDashboardSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weigh-bridge': {
      id: '/weigh-bridge'
      path: '/weigh-bridge'
      fullPath: '/weigh-bridge'
      preLoaderRoute: typeof WeighBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dams': {
      id: '/dams'
      path: '/dams'
      fullPath: '/dams'
      preLoaderRoute: typeof DamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/api/trucks': {
      id: '/api/trucks'
      path: '/api/trucks'
      fullPath: '/api/trucks'
      preLoaderRoute: typeof ApiTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loads': {
      id: '/api/loads'
      path: '/api/loads'
      fullPath: '/api/loads'
      preLoaderRoute: typeof ApiLoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dams': {
      id: '/api/dams'
      path: '/api/dams'
      fullPath: '/api/dams'
      preLoaderRoute: typeof ApiDamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs': {
      id: '/api/audit-logs'
      path: '/api/audit-logs'
      fullPath: '/api/audit-logs'
      preLoaderRoute: typeof ApiAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trucks/$id': {
      id: '/api/trucks/$id'
      path: '/$id'
      fullPath: '/api/trucks/$id'
      preLoaderRoute: typeof ApiTrucksIdRouteImport
      parentRoute: typeof ApiTrucksRoute
    }
    '/api/reports/$id': {
      id: '/api/reports/$id'
      path: '/$id'
      fullPath: '/api/reports/$id'
      preLoaderRoute: typeof ApiReportsIdRouteImport
      parentRoute: typeof ApiReportsRoute
    }
    '/api/dashboard/summary': {
      id: '/api/dashboard/summary'
      path: '/api/dashboard/summary'
      fullPath: '/api/dashboard/summary'
      preLoaderRoute: typeof ApiDashboardSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dams/$id': {
      id: '/api/dams/$id'
      path: '/$id'
      fullPath: '/api/dams/$id'
      preLoaderRoute: typeof ApiDamsIdRouteImport
      parentRoute: typeof ApiDamsRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id/versions': {
      id: '/api/reports/$id/versions'
      path: '/versions'
      fullPath: '/api/reports/$id/versions'
      preLoaderRoute: typeof ApiReportsIdVersionsRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reports/$id/download': {
      id: '/api/reports/$id/download'
      path: '/download'
      fullPath: '/api/reports/$id/download'
      preLoaderRoute: typeof ApiReportsIdDownloadRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ApiDamsRouteChildren {
  ApiDamsIdRoute: typeof ApiDamsIdRoute
}

const ApiDamsRouteChildren: ApiDamsRouteChildren = {
  ApiDamsIdRoute: ApiDamsIdRoute,
}

const ApiDamsRouteWithChildren =
  ApiDamsRoute._addFileChildren(ApiDamsRouteChildren)

interface ApiReportsIdRouteChildren {
  ApiReportsIdDownloadRoute: typeof ApiReportsIdDownloadRoute
  ApiReportsIdVersionsRoute: typeof ApiReportsIdVersionsRoute
}

const ApiReportsIdRouteChildren: ApiReportsIdRouteChildren = {
  ApiReportsIdDownloadRoute: ApiReportsIdDownloadRoute,
  ApiReportsIdVersionsRoute: ApiReportsIdVersionsRoute,
}

const ApiReportsIdRouteWithChildren = ApiReportsIdRoute._addFileChildren(
  ApiReportsIdRouteChildren,
)

interface ApiReportsRouteChildren {
  ApiReportsIdRoute: typeof ApiReportsIdRouteWithChildren
}

const ApiReportsRouteChildren: ApiReportsRouteChildren = {
  ApiReportsIdRoute: ApiReportsIdRouteWithChildren,
}

const ApiReportsRouteWithChildren = ApiReportsRoute._addFileChildren(
  ApiReportsRouteChildren,
)

interface ApiTrucksRouteChildren {
  ApiTrucksIdRoute: typeof ApiTrucksIdRoute
}

const ApiTrucksRouteChildren: ApiTrucksRouteChildren = {
  ApiTrucksIdRoute: ApiTrucksIdRoute,
}

const ApiTrucksRouteWithChildren = ApiTrucksRoute._addFileChildren(
  ApiTrucksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  DamsRoute: DamsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  ImportRoute: ImportRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WeighBridgeRoute: WeighBridgeRoute,
  ApiAuditLogsRoute: ApiAuditLogsRoute,
  ApiDamsRoute: ApiDamsRouteWithChildren,
  ApiLoadsRoute: ApiLoadsRoute,
  ApiReportsRoute: ApiReportsRouteWithChildren,
  ApiTrucksRoute: ApiTrucksRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDashboardSummaryRoute: ApiDashboardSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
