/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeighBridgeRouteImport } from './routes/weigh-bridge'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DamsRouteImport } from './routes/dams'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovementsNewRouteImport } from './routes/movements.new'
import { Route as ApiTrucksRouteImport } from './routes/api.trucks'
import { Route as ApiReportsRouteImport } from './routes/api.reports'
import { Route as ApiLoadsRouteImport } from './routes/api.loads'
import { Route as ApiDamsRouteImport } from './routes/api.dams'
import { Route as ApiAuditLogsRouteImport } from './routes/api.audit-logs'
import { Route as ApiTrucksIdRouteImport } from './routes/api.trucks.$id'
import { Route as ApiReportsVersionsRouteImport } from './routes/api.reports..versions'
import { Route as ApiReportsDownloadRouteImport } from './routes/api.reports..download'
import { Route as ApiDashboardSummaryRouteImport } from './routes/api.dashboard.summary'
import { Route as ApiDamsIdRouteImport } from './routes/api.dams.$id'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiReportsRouteImport } from './routes/api.reports.'

const WeighBridgeRoute = WeighBridgeRouteImport.update({
  id: '/weigh-bridge',
  path: '/weigh-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DamsRoute = DamsRouteImport.update({
  id: '/dams',
  path: '/dams',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsNewRoute = MovementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MovementsRoute,
} as any)
const ApiTrucksRoute = ApiTrucksRouteImport.update({
  id: '/api/trucks',
  path: '/api/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadsRoute = ApiLoadsRouteImport.update({
  id: '/api/loads',
  path: '/api/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDamsRoute = ApiDamsRouteImport.update({
  id: '/api/dams',
  path: '/api/dams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsRoute = ApiAuditLogsRouteImport.update({
  id: '/api/audit-logs',
  path: '/api/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrucksIdRoute = ApiTrucksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTrucksRoute,
} as any)
const ApiReportsVersionsRoute = ApiReportsVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiReportsRoute,
} as any)
const ApiReportsDownloadRoute = ApiReportsDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiReportsRoute,
} as any)
const ApiDashboardSummaryRoute = ApiDashboardSummaryRouteImport.update({
  id: '/api/dashboard/summary',
  path: '/api/dashboard/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDamsIdRoute = ApiDamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDamsRoute,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dams': typeof DamsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/movements': typeof MovementsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/weigh-bridge': typeof WeighBridgeRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/dams': typeof ApiDamsRouteWithChildren
  '/api/loads': typeof ApiLoadsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/trucks': typeof ApiTrucksRouteWithChildren
  '/movements/new': typeof MovementsNewRoute
  '/api/reports/': typeof ApiReportsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dams/$id': typeof ApiDamsIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/reports/download': typeof ApiReportsDownloadRoute
  '/api/reports/versions': typeof ApiReportsVersionsRoute
  '/api/trucks/$id': typeof ApiTrucksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dams': typeof DamsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/movements': typeof MovementsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/weigh-bridge': typeof WeighBridgeRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/dams': typeof ApiDamsRouteWithChildren
  '/api/loads': typeof ApiLoadsRoute
  '/api/trucks': typeof ApiTrucksRouteWithChildren
  '/movements/new': typeof MovementsNewRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dams/$id': typeof ApiDamsIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/reports/download': typeof ApiReportsDownloadRoute
  '/api/reports/versions': typeof ApiReportsVersionsRoute
  '/api/trucks/$id': typeof ApiTrucksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dams': typeof DamsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/movements': typeof MovementsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/weigh-bridge': typeof WeighBridgeRoute
  '/api/audit-logs': typeof ApiAuditLogsRoute
  '/api/dams': typeof ApiDamsRouteWithChildren
  '/api/loads': typeof ApiLoadsRoute
  '/api/reports': typeof ApiReportsRouteWithChildren
  '/api/trucks': typeof ApiTrucksRouteWithChildren
  '/movements/new': typeof MovementsNewRoute
  '/api/reports/': typeof ApiReportsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dams/$id': typeof ApiDamsIdRoute
  '/api/dashboard/summary': typeof ApiDashboardSummaryRoute
  '/api/reports/download': typeof ApiReportsDownloadRoute
  '/api/reports/versions': typeof ApiReportsVersionsRoute
  '/api/trucks/$id': typeof ApiTrucksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/dams'
    | '/dashboard'
    | '/history'
    | '/movements'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/users'
    | '/weigh-bridge'
    | '/api/audit-logs'
    | '/api/dams'
    | '/api/loads'
    | '/api/reports'
    | '/api/trucks'
    | '/movements/new'
    | '/api/reports/'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/dams/$id'
    | '/api/dashboard/summary'
    | '/api/reports/download'
    | '/api/reports/versions'
    | '/api/trucks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/dams'
    | '/dashboard'
    | '/history'
    | '/movements'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/users'
    | '/weigh-bridge'
    | '/api/audit-logs'
    | '/api/dams'
    | '/api/loads'
    | '/api/trucks'
    | '/movements/new'
    | '/api/reports'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/dams/$id'
    | '/api/dashboard/summary'
    | '/api/reports/download'
    | '/api/reports/versions'
    | '/api/trucks/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/dams'
    | '/dashboard'
    | '/history'
    | '/movements'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/users'
    | '/weigh-bridge'
    | '/api/audit-logs'
    | '/api/dams'
    | '/api/loads'
    | '/api/reports'
    | '/api/trucks'
    | '/movements/new'
    | '/api/reports/'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/dams/$id'
    | '/api/dashboard/summary'
    | '/api/reports/download'
    | '/api/reports/versions'
    | '/api/trucks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  DamsRoute: typeof DamsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  MovementsRoute: typeof MovementsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WeighBridgeRoute: typeof WeighBridgeRoute
  ApiAuditLogsRoute: typeof ApiAuditLogsRoute
  ApiDamsRoute: typeof ApiDamsRouteWithChildren
  ApiLoadsRoute: typeof ApiLoadsRoute
  ApiReportsRoute: typeof ApiReportsRouteWithChildren
  ApiTrucksRoute: typeof ApiTrucksRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDashboardSummaryRoute: typeof ApiDashboardSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weigh-bridge': {
      id: '/weigh-bridge'
      path: '/weigh-bridge'
      fullPath: '/weigh-bridge'
      preLoaderRoute: typeof WeighBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dams': {
      id: '/dams'
      path: '/dams'
      fullPath: '/dams'
      preLoaderRoute: typeof DamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/new': {
      id: '/movements/new'
      path: '/new'
      fullPath: '/movements/new'
      preLoaderRoute: typeof MovementsNewRouteImport
      parentRoute: typeof MovementsRoute
    }
    '/api/trucks': {
      id: '/api/trucks'
      path: '/api/trucks'
      fullPath: '/api/trucks'
      preLoaderRoute: typeof ApiTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loads': {
      id: '/api/loads'
      path: '/api/loads'
      fullPath: '/api/loads'
      preLoaderRoute: typeof ApiLoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dams': {
      id: '/api/dams'
      path: '/api/dams'
      fullPath: '/api/dams'
      preLoaderRoute: typeof ApiDamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs': {
      id: '/api/audit-logs'
      path: '/api/audit-logs'
      fullPath: '/api/audit-logs'
      preLoaderRoute: typeof ApiAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trucks/$id': {
      id: '/api/trucks/$id'
      path: '/$id'
      fullPath: '/api/trucks/$id'
      preLoaderRoute: typeof ApiTrucksIdRouteImport
      parentRoute: typeof ApiTrucksRoute
    }
    '/api/reports/versions': {
      id: '/api/reports/versions'
      path: '/versions'
      fullPath: '/api/reports/versions'
      preLoaderRoute: typeof ApiReportsVersionsRouteImport
      parentRoute: typeof ApiReportsRoute
    }
    '/api/reports/download': {
      id: '/api/reports/download'
      path: '/download'
      fullPath: '/api/reports/download'
      preLoaderRoute: typeof ApiReportsDownloadRouteImport
      parentRoute: typeof ApiReportsRoute
    }
    '/api/dashboard/summary': {
      id: '/api/dashboard/summary'
      path: '/api/dashboard/summary'
      fullPath: '/api/dashboard/summary'
      preLoaderRoute: typeof ApiDashboardSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dams/$id': {
      id: '/api/dams/$id'
      path: '/$id'
      fullPath: '/api/dams/$id'
      preLoaderRoute: typeof ApiDamsIdRouteImport
      parentRoute: typeof ApiDamsRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/': {
      id: '/api/reports/'
      path: '/'
      fullPath: '/api/reports/'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof ApiReportsRoute
    }
  }
}

interface MovementsRouteChildren {
  MovementsNewRoute: typeof MovementsNewRoute
}

const MovementsRouteChildren: MovementsRouteChildren = {
  MovementsNewRoute: MovementsNewRoute,
}

const MovementsRouteWithChildren = MovementsRoute._addFileChildren(
  MovementsRouteChildren,
)

interface ApiDamsRouteChildren {
  ApiDamsIdRoute: typeof ApiDamsIdRoute
}

const ApiDamsRouteChildren: ApiDamsRouteChildren = {
  ApiDamsIdRoute: ApiDamsIdRoute,
}

const ApiDamsRouteWithChildren =
  ApiDamsRoute._addFileChildren(ApiDamsRouteChildren)

interface ApiReportsRouteChildren {
  ApiReportsRoute: typeof ApiReportsRoute
  ApiReportsDownloadRoute: typeof ApiReportsDownloadRoute
  ApiReportsVersionsRoute: typeof ApiReportsVersionsRoute
}

const ApiReportsRouteChildren: ApiReportsRouteChildren = {
  ApiReportsRoute: ApiReportsRoute,
  ApiReportsDownloadRoute: ApiReportsDownloadRoute,
  ApiReportsVersionsRoute: ApiReportsVersionsRoute,
}

const ApiReportsRouteWithChildren = ApiReportsRoute._addFileChildren(
  ApiReportsRouteChildren,
)

interface ApiTrucksRouteChildren {
  ApiTrucksIdRoute: typeof ApiTrucksIdRoute
}

const ApiTrucksRouteChildren: ApiTrucksRouteChildren = {
  ApiTrucksIdRoute: ApiTrucksIdRoute,
}

const ApiTrucksRouteWithChildren = ApiTrucksRoute._addFileChildren(
  ApiTrucksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  DamsRoute: DamsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  MovementsRoute: MovementsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WeighBridgeRoute: WeighBridgeRoute,
  ApiAuditLogsRoute: ApiAuditLogsRoute,
  ApiDamsRoute: ApiDamsRouteWithChildren,
  ApiLoadsRoute: ApiLoadsRoute,
  ApiReportsRoute: ApiReportsRouteWithChildren,
  ApiTrucksRoute: ApiTrucksRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDashboardSummaryRoute: ApiDashboardSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
